common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/imu"

preprocess:
    scan_line: 1
    blind: 0.05

mapping:
    acc_cov: 0.5
    gyr_cov: 0.5
    b_acc_cov: 0.0005
    b_gyr_cov: 0.0005
    det_range:     260.0
    extrinsic_T: [ 0.0078, 0.13, 0.0509 ]
    extrinsic_R: [ 1.0, 0.0, 0.0,
                   0.0, 1.0, 0.0,
                   0.0, 0.0, 1.0]

